### ISSUE TITLE
Latest release is still reporting 0.5.1 in getVersion(), so it looks like it is never getting updated in CP

### ISSUE THREAD

**Issue by mildlygeeky** [nfourtythree/craft-entriessubset#5]

**Comment by nfourtythree** [comment]
Good spot @mildlygeeky ! I had noticed only this morning when I was working with it that it was reporting an update.

Thought to myself "I haven't updated it" and then forgot about it. Thanks for pointing it out

It is now fixed in the latest release:
https://github.com/nfourtythree/craft-entriessubset/releases/tag/0.5.4
